-- TABLES

-- tasks table 
create table public.tasks (
  id bigint generated by default as identity primary key,

  uuid uuid not null default gen_random_uuid(),

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  title text not null,

  description text,

  priority smallint not null default 2
    check (priority between 1 and 3),

  is_completed boolean not null default false,

  scheduled_for date not null
    default (current_date + interval '1 day'),

  postpone_count integer not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_on timestamptz
);


-- notes table 
create table public.notes (
  id bigint generated by default as identity primary key,

  uuid uuid not null default gen_random_uuid(),

  user_id uuid not null
    references auth.users(id)
    on delete cascade,

  title text not null,

  content text not null,

  tags text[] not null default '{}',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);



-- RLS POLICIES
alter table public.tasks enable row level security;
alter table public.notes enable row level security;


create policy "Users can manage their own tasks"
on public.tasks
for all
using (auth.uid() = user_id);


create policy "Users can manage their own notes"
on public.notes
for all
using (auth.uid() = user_id);



-- INDEX for db performances

--tasks: User + scheduled day
create index idx_tasks_user_scheduled
on public.tasks (user_id, scheduled_for);


--tasks: for incomplete and complete tasks
create index idx_tasks_user_completed
on public.tasks (user_id, is_completed);

--tasks: priority
create index idx_tasks_user_priority
on public.tasks (user_id, priority);


-- notes: filter notes by user
create index idx_notes_user
on public.notes (user_id);


